import Head from 'next/head';
import { DM_Sans } from 'next/font/google';

import '@/styles/globals.scss';
import { useEffect, useState } from 'react';

const dmSans = DM_Sans({
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
});

export default function App({ Component, pageProps }) {
  const [isLoaded, setIsLoaded] = useState(false);

  useEffect(() => {
    setIsLoaded(true); // This is to fix the hydration issue with the useLayoutEffect.
  }, []);

  return (
    <>
      <style jsx global>
        {`
          html {
            font-family: ${dmSans.style.fontFamily};
          }
        `}
      </style>
      <Head>
        <title>Dog Aging Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page-container">
        {isLoaded && <Component {...pageProps} />}
      </div>
    </>
  );
}
